name: Build/Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Build Application
        run: pnpm run build

      - name: Build/Release Electron App (macOS)
        if: matrix.os == 'macos-latest'
        run: pnpm run dist:mac

      - name: Build/Release Electron App (Linux)  
        if: matrix.os == 'ubuntu-latest'
        run: pnpm run dist:linux

      - name: Build/Release Electron App (Windows)
        if: matrix.os == 'windows-latest'
        run: pnpm run dist:win

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: dist/packages/*